== Forord til den engelske originalversjonen

Alle som arbeider med terminologi, for eksempel med å utarbeide en termliste, må vite hvor de kan finne svar på en rekke spørsmål, før de i det hele tatt kan begynne på selve arbeidet. Hvor begynner man, hvor finner man pålitelige kilder, og hva slags opplysninger skal man samle inn? Hvordan strukturerer og registrerer man opplysningene, og når er datamaskinen et nyttig hjelpemiddel? Hvordan skiller man de forskjellige språkene fra hverandre, hvordan skriver man definisjoner, og hvordan organiserer man hele arbeidsprosessen? Slike spørsmål dukker opp hver gang et terminologi­ prosjekt blir satt i gang, og derfor er det fornuftig å forsøke å benytte løsninger som allerede er utprøvd. De metodene som benyttes ved prosjektarbeid, egner seg godt også til terminologiarbeid. Til og med praktiske småting som volder bry i arbeidet, er ofte av en slik art at standardiserte metoder eller modeller kan være til hjelp. En oversikt over nyttige standarder er oppført [.line-through]#på sidene 45–46#[under <<Referanser til aktuelle standarder>>].

Andre og mindre vanlige spørsmål gjelder kvaliteten på termlista. Ofte dukker ikke spørsmålet om kvalitet opp før mot slutten av terminologiprosjektet, eller først når termlista er gitt ut. For selv om en termsamling bygger på best mulige kilder, bør den ikke gis ut før den er bearbeidet. Det viktigste kjennetegnet på kvalitet i en term­ liste er indre sammenheng i innholdet. Det vil si at det må være klare relasjoner mellom begrepene, og det kommer til uttrykk i entydige definisjoner og termer som ikke motsier hverandre. En slik struktur oppnås bare når materialet utarbeides systematisk. Formålet med dette heftet er å gi en kort innføring i prinsippene og metodene for systematisk terminologiarbeid og vise hvordan de kan utnyttes i praksis. Heftet inneholder derfor ikke alle de opplysninger man trenger. Ytterligere opplysninger er imidlertid å finne i standardene nevnt ovenfor. De bør være obligatorisk lesning for dem som leder terminologiske arbeidsgrupper. Det som imidlertid er mest verdifullt i terminologiarbeid, er lang erfaring og praksis på området. Derfor kan en erfaren terminolog tilby uunnværlig hjelp til å overvinne de hindringene som uunngåelig dukker opp i alle terminologi­ prosjekter. Arbeidsgrupper som tar fatt på et terminologiprosjekt for første gang, oppfordres derfor innstendig til å ta kontakt med en erfaren terminolog når det er mulig.

Selv om systematisk terminologiarbeid åpenbart bidrar til økt kvalitet, kan førsteinntrykket være at metoden er altfor komplisert, tidkrevende og kostbar. Det stemmer imidlertid ikke. Lang erfaring og statistikk fra tidligere prosjekter viser at bruk av terminologiske metoder faktisk fører til kortere prosjekttid og betydelig lavere totalkostnader så snart den første læringsterskelen er passert.

Dette heftet er et sideprodukt av internasjonal standardisering. Det opprinnelige initiativet kom fra brukere som mente at de behøvde en kortfattet innføring i prinsippene og metodene for praktisk terminologiarbeid. En rekke høyt verdsatte kolleger og terminologi­ interesserte fageksperter fra Norge, Sverige, Finland, Canada og Østerrike har vært til stor hjelp for meg med nyttige og innsiktsfulle kommentarer. Jeg vil med dette takke dem alle sammen.

Helsingfors i desember 1996

Heidi Suonuuti
