== Forord til den norske versjonen

Fagspråk er en viktig arena for utviklingen av ordforrådet i et språk. På de aller fleste fagområder oppstår det jevnlig nye begreper med tilhørende betegnelser, det vil si termer. Mange av dem tas i bruk også i allmennspråket, i dag ikke minst innenfor databehandling og kommunikasjon over Internett.

Språkrådets forgjenger, Norsk språkråd (1972–2004), var engasjert i norsk terminologiutvikling og deltok i komité­ og prosjektarbeid på området. Språkrådet er ikke mindre opptatt av norsk fagspråk; et av institusjonens fire ytre fagråd har nettopp terminologi og fagspråk som sitt ansvarsområde.

Den tiltakende internasjonaliseringen har ført til økt bruk av engelsk språk i fagkommunikasjon i de fleste industrialiserte land, så vel i forskning og utvikling som i undervisning og publisering. Det vekker bekymring fordi det i nasjonalspråk som norsk dermed i mindre grad enn før blir utviklet ny terminologi. Enkelte frykter at følgen kan bli at norsk i framtida ikke lenger vil være et fullgodt ut­trykksmiddel i tale og skrift på alle fag­ og samfunnsområder.

Dette heftet blir gitt ut som et ledd i bestrebelsene på å styrke norsk fagspråk. Heidi Suonuutis _Guide to Terminology_ gir en grunnleggende innføring i begrepsanalyse og terminologiarbeid. Vårt håp er at innholdet kan stimulere interessen for arbeid med norsk terminologi og styrke bevisstheten om at det er maktpåliggende å ivareta denne delen av morsmålets ordforråd. Målgruppen er alle som er interessert i begrepsanalyse og terminologi. Ikke minst vil fagfolk og (fag)oversettere kunne ha utbytte av innholdet. Heftet kan dessuten med fordel brukes som en innføring i emnet for studenter, innenfor både tekniske og humanistiske fag.

Hovedtittelen på den norske versjonen er _Termlosen_. Med den øns­ker vi å tydeliggjøre at heftet ikke er en uttømmende lærebok, men snarere en veiviser gjennom de mest grunnleggende prinsippene og arbeidsmetodene på området. Tillegget <<Termleia>> er en kortfattet veiledning som trinn for trinn viser vei i praktisk terminologiarbeid og dessuten kan benyttes som sjekkliste.

Den norske versjonen følger i all hovedsak den engelske originalen, men avviker på noen punkter og følger da den svenske versjonen. <<Oversikt over anvendte termer, Oversikten over anvendte termer>> [.line-through]#med sidehenvisning (s. 41–43)# og <<Nordterms organisasjoner>> [.line-through]#(s. 44)# er oppdatert, i likhet med fortegnelsen over <<Referanser til aktuelle standarder, referanser til aktuelle standarder>> [.line-through]#(s. 45–46)#. Sistnevnte fortegnelse og <<Termleia>> er dessuten flyttet bakerst i heftet. Overset­telsen – som dels er på bokmål, dels på nynorsk – er gjennomgått, kommentert og godkjent av forfatteren.

Vi retter en stor takk til Heidi Suonuuti for at vi får gi ut en norsk versjon. Oversetteren fortjener ros for sitt solide arbeid og store tål­modighet! Vi takker også Johan Myking ved Universitetet i Bergen og flere personer ved Standard Norge som har bidratt med forslag, råd og opplysninger. Torbjørg Breivik i Språkrådet deltok i arbeidet på et innledende stadium.

Oslo i juni 2008 +
Jan Hoel, Språkrådet

Etterspørselen etter _Termlosen_ har vært stor. Det første opplaget på 1 000 eksemplarer er revet unna på 20 måneder. Det er med stor glede vi nå gir ut et nytt, rettet opplag. Det dreier seg om noen mindre språklige rettelser og faktaendringer som ikke endrer den norske versjonen i nevneverdig grad. Vi håper det nye opplaget blir like populært som det første.

Oslo i april 2010 +
Jan Hoel, Språkrådet

Gledelig nok er det igjen blitt nødvendig å trykke opp et nytt opplag på 1 000 eksemplarer. Noen opplysninger er samtidig blitt oppdatert.

Oslo i juni 2012 +
Jan Hoel, Språkrådet

Nok et ajourført opplag på 1 000 eksemplarer er trykket opp.

Oslo i mars 2015 +
Jan Hoel, Språkrådet

Et rettet og ajourført opplag er trykket opp.

Oslo i juni 2020 +
Marianne Aasgaard o.a., Språkrådet
