== Forord til andre utgave av den engelske originalversjonen

Den reviderte andre utgaven av _Guide to Terminology_ inneholder bare noen få endringer, som skyldes at åpenbare feil og utelatelser er rettet.

Da _Guide to Terminology_ opprinnelig ble utarbeidet i 1996, fantes det ennå ikke noen enkel og kortfattet veiledning i terminologiarbeid. De internasjonale standardene var altfor teoretiske og innviklede for praktisk terminologiarbeid, og reviderte utgaver av dem var fremdeles bare på planleggingsstadiet. Vanligvis blir fagordlister utarbeidet av grupper med representanter for det aktuelle fagområdet. Slike grupper misliker ofte teori fordi de syns den er forholdsvis unyttig. Derfor følte de behov for en veiledning som med eksempler presenterte det minimum av teori som er nødvendig for terminologiarbeid. At det var behov for veiledningen, ble etter min oppfatning bekreftet ved at den snart ble oversatt til fire språk: esperanto, kroa­tisk, kinesisk og spansk (sistnevnte er imidlertid ikke gitt ut ennå).

I de seneste årene er det gitt ut et nytt sett internasjonale standarder. De er mer praktisk vinklet og mer kortfattede enn tidligere. Likevel virker det som om dette heftet fortsatt forsvarer sin plass som en innføring i terminologiens verden.

Helsingfors i september 2001

Heidi Suonuuti
