name: Build adocs and publish develop to Github-pages

on:
  push:
    branches:
      - develop
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: asciidoctor build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build html nn
        id: adocbuild_nn
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor -D docs -o index-nn.html -a lang=nn docs/main.adoc"

      - name: Build html nb
        id: adocbuild_nb
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor -D docs -o index-nb.html -a lang=nb docs/main.adoc"
      - name: Build pdf
        id: adocbuild_pdf
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf -D docs -o files/termlosen.pdf -a lang=nn docs/main.adoc"
        continue-on-error: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
