name: Build adocs and publish v1 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload specification to static-rdf-server
    if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/v1'
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v1
      program_html: |
        asciidoctor -D docs -o termlosen-nn.html -a lang=nn docs/main.adoc
        asciidoctor -D docs -o termlosen-nb.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/termlosen.pdf -a lang=nn docs/main.adoc
      program_pdf_continue_on_error: true
      host: https://data.norge.no
      ontology: termlosen
      ontology-type: specification
      files: |
        docs/termlosen-nb.html text/html nb
        docs/termlosen-nn.html text/html nn
        docs/files/termlosen.pdf application/pdf nn files/termlosen.pdf
        docs/images/logoene.png image/png nn images/logoene.png
        docs/images/Fig1.png image/png nn images/Fig1.png
        docs/images/Fig2.png image/png nn images/Fig2.png
        docs/images/Fig3.png image/png nn images/Fig3.png
        docs/images/Fig4.png image/png nn images/Fig4.png
        docs/images/Fig5.png image/png nn images/Fig5.png
        docs/images/Fig6.png image/png nn images/Fig6.png
        docs/images/Fig7.png image/png nn images/Fig7.png
        docs/images/Fig8.png image/png nn images/Fig8.png
        docs/images/Fig9.png image/png nn images/Fig9.png
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
